remote_theme: pages-themes/cayman@v0.2.0
plugins:
- jekyll-remote-theme # add this line to the plugins list if you already have one
title: [Apuntes contenedores. Docker]
description: [Apuntes de introducción a la gestión de contenedores Docker para la asignatura de servicios en red de segundo de ASIR]
